### ISSUE TITLE
src/linp-doorbell.h:2:19: fatal error: Queue.h: No such file or directory

### ISSUE THREAD

**Issue by DirkTas67** [pauln/esphome-linp-doorbell-g03#12]
In file included from src/main.cpp:50:0:
src/linp-doorbell.h:2:19: fatal error: Queue.h: No such file or directory

***************************************************************
* Looking for Queue.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Queue.h"
* Web  > https://platformio.org/lib/search?query=header:Queue.h
*
***************************************************************

compilation terminated.
*** [/data/esp32_g03_deurbel_voordeur/.pioenvs/esp32_g03_deurbel_voordeur/src/main.cpp.o] Error 1
========================= [FAILED] Took 57.66 seconds =========================

->
Looking for AsyncTCP-esphome library in registry
LibraryManager: Installing id=6798 @ 1.1.1
AsyncTCP-esphome @ 1.1.1 has been successfully installed!
Looking for ArduinoQueue library in registry
LibraryManager: Installing id=5826
ArduinoQueue @ 1.2.3 has been successfully installed!
Looking for ESPAsyncWebServer-esphome library in registry
LibraryManager: Installing id=6758 @ 1.2.6
ESPAsyncWebServer-esphome @ 1.2.6 has been successfully installed!
Looking for ESPAsyncTCP-esphome library in registry
LibraryManager: Installing id=6757
ESPAsyncTCP-esphome @ 1.2.2 has been successfully installed!
LibraryManager: Installing id=6798
Looking for ArduinoJson-esphomelib library in registry
LibraryManager: Installing id=3837 @ 5.13.3
ArduinoJson-esphomelib @ 5.13.3 has been successfully installed!

->
Any ideas's?

Regards
Dirk

**Comment by vencakratky** [comment]
I have the same Issue on compiling on Home Assistant ESPHome 
`In file included from src/main.cpp:32:0:
src/linp-doorbell.h:2:19: fatal error: Queue.h: No such file or directory

***************************************************************
* Looking for Queue.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Queue.h"
* Web  > https://platformio.org/lib/search?query=header:Queue.h
*
***************************************************************

compilation terminated.
*** [/data/linp_doorbell/.pioenvs/linp_doorbell/src/main.cpp.o] Error 1
========================= [FAILED] Took 49.08 seconds =========================`

**Comment by Thomasv1212** [comment]
Anyone a solution jet?

**Comment by bonuzzz** [comment]
solution is here:
https://github.com/pauln/esphome-linp-doorbell-g03/pull/11

**Comment by DirkTas67** [comment]
if you look in my first message you see the following -> Looking for ArduinoQueue library in registry

So the library is loaded, I downloaded the latest version of the files here but still get this error.

**Comment by bonuzzz** [comment]
but also you should edit linp-doorbell.h file
https://github.com/pauln/esphome-linp-doorbell-g03/pull/11/files

**Comment by vencakratky** [comment]
Yes, after edit linp-doorbell.h it´s working. Thank you :) 
![linp](https://user-images.githubusercontent.com/54419577/87765208-d5809c00-c817-11ea-8e54-ba989e229329.jpg)

**Comment by DirkTas67** [comment]
Thank you, this is solved.
