### ISSUE TITLE
Update firmware over OTA in default setting (linp-doorbell.yaml)

### ISSUE THREAD

**Issue by vencakratky** [pauln/esphome-linp-doorbell-g03#14]
Hello, i am rookie in ESP and 2 Months ago i tried this "hack" for linp doorbell over Serial-USB adapter. All is OK, thank you for great tutorial. Now i see, it´s possible new Firmware, but i thinked, in default setting is possible OTA update. Unfortunately, it reports an error (Connection refused) when trying to update:
![OTA](https://user-images.githubusercontent.com/54419577/94235468-edf1ee80-ff0b-11ea-86a2-3e9132b7242b.jpg)
After some searching, I found that the file "linp-doorbell.yaml" should contain string "ota:"
Is there now some way to successfully update via OTA ? Or do I have to use the Serial-USB adapter again? - now with "ota:"  strings in linp-doorbell.yaml? 
Thank you

**Comment by pauln** [comment]
If you didn't include the `ota:` section in your yaml config, you'll need to use the serial USB adapter to update, sorry.  I'll add an `ota:` section to the example config so that hopefully nobody else misses adding it (if they want to enable OTA updates).
