### ISSUE TITLE
How do I get into flash mode?

### ISSUE THREAD

**Issue by 9werayut** [pauln/esphome-linp-doorbell-g03#15]
I don't understand how to describe flash mode. Would you describe it as a picture? Will you have a video?

**Comment by 9werayut** [comment]
![S__17899673](https://user-images.githubusercontent.com/14170462/107867899-a0bdeb80-6eb1-11eb-84d7-2fe5d3825706.jpg)

**Comment by timmmmmmmmm** [comment]
Does this help? https://github.com/pauln/esphome-linp-doorbell-g03/issues/8

**Comment by 9werayut** [comment]
> Does this help? #8

Thanks for helping, I can do it
