### ISSUE TITLE
Help, identify resistor

### ISSUE THREAD

**Issue by stevoh6** [pauln/esphome-linp-doorbell-g03#17]
Hi, please could somebody make picture of his board, or write here params of this resistor? He didnt make it. 
Thanks.
![IMG_20210429_141341__01__01__01](https://user-images.githubusercontent.com/7179591/116549528-e3f6fa80-a8f5-11eb-9c98-caf627b63f52.jpg)

**Comment by pauln** [comment]
Wow, how did you manage that?!  It appears to be a 47 ohm resistor (5% tolerance) - the colours are yellow/violet/black/gold.

**Comment by stevoh6** [comment]
Thank you :-) I pug it into socket and it make a puff :D. Anyway, how many watts it should handle? 1W, 2w or 3w?

**Comment by pauln** [comment]
Based on the size, I'd guess 1W.  Hopefully it did its job as a fuse successfully and protected the rest of the board - and hopefully you can figure out what happened and stop it from happening again!

**Comment by stevoh6** [comment]
I will let you know, I'm guessing two things: 
1) I little adjust position of this resistor to be able put it into the plastic cover (there was a crack after puff, maybe this crack was here before)
2) not properly clean board from flux after soldering
