### ISSUE TITLE
Firmware compilation error

### ISSUE THREAD

**Issue by NerijusKavaliunas** [pauln/esphome-linp-doorbell-g03#20]
Hi there,
trying to compile firmware for my doorbell with no luck. Getting error - please see attached picture.
Seems that there is missing file - "esp_idf_version.h".
What should i do to fix it?
Thank you.
![Screenshot_20211019_145140](https://user-images.githubusercontent.com/34972376/137904244-a630c5ba-2eeb-4485-ab6a-58fe9ef20bd1.png)

**Comment by 000al000** [comment]
try use esphome 2021.8

**Comment by NerijusKavaliunas** [comment]
With 2021.8 got it working. Thanks

**Comment by NerijusKavaliunas** [comment]
This issue is closed. Thanks **000al000** for a help.
