### ISSUE TITLE
Different pins layout

### ISSUE THREAD

**Issue by GenoMXXX** [pauln/esphome-linp-doorbell-g03#22]
I have a different pins layout. Tell me, please, where I can fix it.
Thanks! 
![photo_2021-11-30_15-44-00](https://user-images.githubusercontent.com/60142384/144049719-6fe61c6f-4337-4d0f-9934-46a7b4dcac21.jpg)

**Comment by pauln** [comment]
Hi, it looks as though there's a completely new board revision - which this component won't work on.  I'll close this in favour of #23  as it looks as though it may be the same revision, and there's more detail over there - if your board looks different to the photos in that thread, please post full photos of both sides of the board in that thread to help identify any differences.
